version: "3.8"

services:

  backend:
    container_name: "bsbe"
    build: ./services/backend
    ports:
      - "8000:8000"
    volumes:
      - './services/backend:/app'
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    networks:
      - local-net

  frontend:
    container_name: "bsfe"
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    volumes:
      - './services/frontend:/app'
    ports:
      - "8080:8080"

networks:
  local-net:
    driver: bridge